import { transportSummaryEnum } from "@/enum/transport";
import {
  SidebarAccounts,
  SidebarAdmin,
  SidebarCalendar,
  SidebarContracts,
  SidebarEmployees,
  SidebarHome,
  SidebarMedical,
  SidebarRequests,
  SidebarSetup,
  SidebarTimesheets,
  TruckIcon,
} from "@/components/svgIcons";
import { FeaturesNameEnum, PermissionEnum } from "@/utils/commonConstants";

export const formatOptionData = [
  {
    label: "Request at start, once only",
    value: "Request at start, once only",
  },
  {
    label: "Request days before expiry",
    value: "Request days before expiry",
  },
  {
    label: "Available anytime",
    value: "Available anytime",
  },
  {
    label: "Tuesdays and Thursdays",
    value: "Tuesdays and Thursdays",
  },
];

export const daysOfWeek = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

export const folderTypeIdList = [
  {
    label: "Default",
    value: 1,
  },
  {
    label: "Approve",
    value: 2,
  },
];

export const transportSummaryTypeList = [
  {
    label: "Transport Model",
    value: transportSummaryEnum.Model,
  },
  {
    label: "Transport Type",
    value: transportSummaryEnum.Type,
  },
  {
    label: "Transport Capacity",
    value: transportSummaryEnum.Capacity,
  },
  {
    label: "Transport Position",
    value: transportSummaryEnum.Position,
  },
];

export const genderOptions = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
];

export const employeeFilterOptions = [
  { label: "All", value: "all" },
  { label: "Active", value: "active" },
  { label: "Terminated", value: "terminated" },
];

export const chartDropdownOptions = [
  { label: "Next 7 days", value: "7" },
  { label: "Next 15 days", value: "15" },
  { label: "Next 30 days", value: "30" },
  { label: "Current Year", value: "365" },
];
export const userChartDropdownOptions = [
  { label: "Last 7 days", value: "7" },
  { label: "Last 15 days", value: "15" },
  { label: "Last 30 days", value: "30" },
  { label: "Current Year", value: "365" },
];
const permissionArray = [
  PermissionEnum.Create,
  PermissionEnum.Update,
  PermissionEnum.Delete,
  PermissionEnum.View,
];
export const MenuList = [
  {
    id: 1,
    name: "Dashboard",
    link: "/",
    icon: SidebarHome,
    subMenu: false,
    featureName: [FeaturesNameEnum.Dashboard],
    permission: permissionArray,
  },
  {
    id: 2,
    name: "Setup",
    link: "#!",
    icon: SidebarSetup,
    subMenu: true,
    featureName: [
      FeaturesNameEnum.Client,
      FeaturesNameEnum.Contact,
      FeaturesNameEnum.Segment,
      FeaturesNameEnum.SubSegment,
      FeaturesNameEnum.BonusType,
      FeaturesNameEnum.Rotation,
      FeaturesNameEnum.Folder,
      FeaturesNameEnum.MedicalType,
      FeaturesNameEnum.RequestType,
    ],
    permission: permissionArray,
    subMenuList: [
      {
        name: "Clients",
        id: "setupClient",
        link: "/setup/clients",
        featureName: [FeaturesNameEnum.Client],
        permission: permissionArray,
      },
      {
        name: "Contacts",
        id: "setupContacts",
        link: "/setup/contacts",
        featureName: [FeaturesNameEnum.Contact],
        permission: permissionArray,
      },
      {
        name: "Segments",
        id: "setupSegments",
        link: "/setup/segments",
        featureName: [FeaturesNameEnum.Segment],
        permission: permissionArray,
      },
      {
        name: "Sub-segments",
        id: "setupSubSegments",
        link: "/setup/sub-segments",
        featureName: [FeaturesNameEnum.SubSegment],
        permission: permissionArray,
      },
      {
        name: "Bonus Types",
        id: "setupBonusTypes",
        link: "/setup/bonus-type",
        featureName: [FeaturesNameEnum.BonusType],
        permission: permissionArray,
      },
      {
        name: "Rotations",
        id: "setupRotations",
        link: "/setup/rotations",
        featureName: [FeaturesNameEnum.Rotation],
        permission: permissionArray,
      },
      {
        name: "Folders",
        id: "setupFolders",
        link: "/setup/folders",
        featureName: [FeaturesNameEnum.Folder],
        permission: permissionArray,
      },
      {
        name: "Medical Types",
        id: "setupMedicalTypes",
        link: "/setup/medical-type",
        featureName: [FeaturesNameEnum.MedicalType],
        permission: permissionArray,
      },
      {
        name: "Request Types",
        id: "setupRequestTypes",
        link: "/setup/request-type",
        featureName: [FeaturesNameEnum.RequestType],
        permission: permissionArray,
      },
    ],
  },
  {
    id: 3,
    name: "Admin",
    link: "#!",
    icon: SidebarAdmin,
    subMenu: true,
    featureName: [
      FeaturesNameEnum.Message,
      FeaturesNameEnum.SalaryMessage,
      FeaturesNameEnum.Role,
      FeaturesNameEnum.ErrorLogs,
      FeaturesNameEnum.Users,
      FeaturesNameEnum.ApproveDeletedFile,
    ],
    permission: permissionArray,
    subMenuList: [
      {
        name: "Messages",
        id: "adminMessages",
        link: "/admin/message",
        featureName: [FeaturesNameEnum.Message],
        permission: permissionArray,
      },
      {
        name: "Salary Messages",
        id: "adminSalaryMessages",
        link: "/admin/salary-message",
        featureName: [FeaturesNameEnum.SalaryMessage],
        permission: permissionArray,
      },
      {
        name: "Role",
        id: "adminRole",
        link: "/admin/role",
        featureName: [FeaturesNameEnum.Role],
        permission: permissionArray,
      },
      {
        name: "Logs",
        id: "adminLogs",
        link: "/admin/error-logs",
        featureName: [FeaturesNameEnum.ErrorLogs],
        permission: permissionArray,
      },
      {
        name: "Users",
        id: "adminUsers",
        link: "/admin/user",
        featureName: [FeaturesNameEnum.Users],
        permission: permissionArray,
      },
      {
        name: "Approve Deleted Files",
        id: "adminApproveDeletedFiles",
        link: "/admin/approve-deleted-file",
        featureName: [FeaturesNameEnum.ApproveDeletedFile],
        permission: permissionArray,
      },
    ],
  },
  {
    id: 4,
    name: "Accounts",
    link: "#!",
    icon: SidebarAccounts,
    featureName: [FeaturesNameEnum.Account],
    permission: permissionArray,
    subMenu: true,
    subMenuList: [
      // {
      //   name: "Summary",
      //   id: "accountSummary",
      //   link: "/accounts/summary",
      //   featureName: [FeaturesNameEnum.Account],
      //   permission: permissionArray,
      // },
      // {
      //   name: "Modify",
      //   id: "accountModifySummary",
      //   link: "/accounts/modify",
      //   featureName: [FeaturesNameEnum.Account],
      //   permission: permissionArray,
      // },
      {
        name: "POs",
        id: "accountPOs",
        link: "/accounts/PO",
        featureName: [FeaturesNameEnum.AccountPO],
        permission: [PermissionEnum.View],
      },
    ],
  },
  {
    id: 5,
    name: "Employees",
    link: "#!",
    icon: SidebarEmployees,
    subMenu: true,
    featureName: [
      FeaturesNameEnum.Employee,
      FeaturesNameEnum.ReliquatCalculation,
      FeaturesNameEnum.ReliquatCalculationV2,
      FeaturesNameEnum.ReliquatAdjustment,
      FeaturesNameEnum.ReliquatPayment,
      FeaturesNameEnum.ImportLog,
    ],
    permission: permissionArray,
    subMenuList: [
      {
        name: "Summary",
        id: "employeeSummary",
        link: "/employee/summary",
        featureName: [FeaturesNameEnum.Employee],
        permission: permissionArray,
      },
      {
        name: "Reliquat Calculations",
        id: "employeeReliquatCalculations",
        link: "/employee/reliquat-calculation",
        featureName: [FeaturesNameEnum.ReliquatCalculation],
        permission: permissionArray,
      },
      // {
      //   name: "Reliquat Calculations v2",
      //   id: "employeeReliquatCalculationsV2",
      //   link: "/employee/reliquat-calculation-v2",
      //   featureName: [FeaturesNameEnum.ReliquatCalculationV2],
      //   permission: permissionArray,
      // },
      {
        name: "Reliquat Adjustments",
        id: "employeeReliquatAdjustments",
        link: "/employee/reliquat-adjustment",
        featureName: [FeaturesNameEnum.ReliquatAdjustment],
        permission: permissionArray,
      },
      {
        name: "Reliquat Payment",
        id: "employeeReliquatPayment",
        link: "/employee/reliquat-payment",
        featureName: [FeaturesNameEnum.ReliquatPayment],
        permission: permissionArray,
      },
      // {
      //   name: "Import",
      //   id: "employeeImport",
      //   link: "/employee/import",
      //   featureName: [FeaturesNameEnum.ImportLog],
      //   permission: [PermissionEnum.Create],
      // },
      // {
      //   name: "Import Logs",
      //   id: "employeeImportLogs",
      //   link: "/employee/import-logs",
      //   featureName: [FeaturesNameEnum.ImportLog],
      //   permission: permissionArray,
      // },
      {
        name: "Export",
        id: "employeeExport",
        link: "/employee/export",
        featureName: [FeaturesNameEnum.Employee],
        permission: permissionArray,
      },
    ],
  },
  {
    id: 6,
    name: "Titre de Congé",
    link: "/employee-leave",
    icon: SidebarCalendar,
    subMenu: false,
    featureName: [FeaturesNameEnum.EmployeeLeave],
    permission: permissionArray,
  },

  {
    id: 7,
    name: "Medical",
    link: "#!",
    icon: SidebarMedical,
    subMenu: true,
    featureName: [FeaturesNameEnum.MedicalRequest],
    permission: permissionArray,
    subMenuList: [
      {
        name: "Summary",
        id: "medical",
        link: "/medical/summary",
        subMenu: false,
        featureName: [FeaturesNameEnum.MedicalRequest],
        permission: permissionArray,
      },
      // {
      //   name: "Expiry",
      //   id: "medicalExpiry",
      //   link: "/medical/expiry",
      //   featureName: [FeaturesNameEnum.MedicalRequest],
      //   permission: permissionArray,
      // },
    ],
  },

  {
    id: 8,
    name: "Timesheets",
    link: "#!",
    icon: SidebarTimesheets,
    subMenu: true,
    featureName: [FeaturesNameEnum.Timesheet],
    permission: permissionArray,
    subMenuList: [
      {
        name: "Summary",
        id: "timesheetsSummary",
        link: "/timesheet/summary",
        featureName: [FeaturesNameEnum.Timesheet],
        permission: permissionArray,
      },
      {
        name: "Modify",
        id: "timesheetsUpdate",
        link: "/timesheet/update",
        featureName: [FeaturesNameEnum.Timesheet],
        permission: [PermissionEnum.View],
      },
    ],
  },
  {
    id: 9,
    name: "Requests",
    link: "/requests",
    icon: SidebarRequests,
    subMenu: false,
    subMenuList: [],
    featureName: [FeaturesNameEnum.Request],
    permission: permissionArray,
  },
  {
    id: 10,
    name: "Contract",
    link: "#!",
    icon: SidebarContracts,
    subMenu: true,
    featureName: [
      FeaturesNameEnum.EmployeeContract,
      FeaturesNameEnum.ContractTemplate,
      FeaturesNameEnum.ContractTemplateVersion,
    ],
    permission: permissionArray,
    subMenuList: [
      {
        name: "Contract Summary",
        id: "contractSummary",
        link: "/contract/summary",
        featureName: [FeaturesNameEnum.EmployeeContract],
        permission: permissionArray,
      },
      {
        name: "Contract Template",
        id: "contractTemplate",
        link: "/contract-template",
        featureName: [FeaturesNameEnum.ContractTemplate],
        permission: permissionArray,
      },

      {
        name: "Contract Versions",
        id: "contractVersions",
        link: "/contract-template-version",
        featureName: [FeaturesNameEnum.ContractTemplateVersion],
        permission: permissionArray,
      },
      {
        name: "Contract End",
        id: "employeeContractEnd",
        link: "/contract/contract-end",
        featureName: [FeaturesNameEnum.ContractEnd],
        permission: [PermissionEnum.View],
      },
    ],
  },
  {
    id: 11,
    name: "Transport",
    link: "#!",
    icon: TruckIcon,
    subMenu: true,
    featureName: [
      FeaturesNameEnum.TransportSummary,
      FeaturesNameEnum.TransportVehicle,
      FeaturesNameEnum.TransportDriver,
      FeaturesNameEnum.TransportRequest,
    ],
    permission: permissionArray,
    subMenuList: [
      {
        name: "Summary",
        id: "transportSetup",
        link: "/transport/summary",
        subMenu: false,
        featureName: [FeaturesNameEnum.TransportSummary],
        permission: permissionArray,
      },
      {
        name: "Vehicles",
        id: "transportVehicles",
        link: "/transport/vehicles",
        featureName: [FeaturesNameEnum.TransportVehicle],
        permission: permissionArray,
      },
      {
        name: "Drivers",
        id: "transportDrivers",
        link: "/transport/drivers",
        featureName: [FeaturesNameEnum.TransportDriver],
        permission: permissionArray,
      },
      {
        name: "Requests",
        id: "transportRequests",
        link: "/transport/requests",
        featureName: [FeaturesNameEnum.TransportRequest],
        permission: permissionArray,
      },
    ],
  },
];

export const pathWiseClientDropDownAvailable = [
  "/",
  "/requests",
  "/medical/expiry",
  "/admin/approve-deleted-file",
  "/setup/contacts",
  "/setup/segments",
  "/setup/sub-segments",
  "/admin/message",
  "/admin/salary-message",
  "/admin/salary-message/draft",
  "/admin/message/add",
  "/admin/message/edit/:id",
  "/admin/error-logs",
  "/employee/summary",
  "/employee/reliquat-adjustment",
  "/employee/reliquat-payment",
  "/employee/reliquat-calculation-v2",
  "/employee/import",
  "/contract/summary/add",
  "/contract/summary/edit/:id",
  "/employee/export",
  "/employee-leave",
  "/medical/summary",
  "/accounts/summary",
  "/accounts/modify",
  "/accounts/PO",
  "/contract/summary",
  "/contract-template-version",
  "/contract-template",
  "/contract/contract-end",
  "/transport/summary",
  "/transport/vehicles",
  "/transport/drivers",
  "/transport/requests",
  "/timesheet/summary",
  "/timesheet/update",
  "/employee/reliquat-calculation",
  "/employee/import-logs",
];
